<?php
add_action( 'init', 'people_register_post_type' );
function people_register_post_type() {
	$labels = [
		'name'                     => esc_html__( 'People', 'your-textdomain' ),
		'singular_name'            => esc_html__( 'People', 'your-textdomain' ),
		'add_new'                  => esc_html__( 'Add New', 'your-textdomain' ),
		'add_new_item'             => esc_html__( 'Add New People', 'your-textdomain' ),
		'edit_item'                => esc_html__( 'Edit People', 'your-textdomain' ),
		'new_item'                 => esc_html__( 'New People', 'your-textdomain' ),
		'view_item'                => esc_html__( 'View People', 'your-textdomain' ),
		'view_items'               => esc_html__( 'View People', 'your-textdomain' ),
		'search_items'             => esc_html__( 'Search People', 'your-textdomain' ),
		'not_found'                => esc_html__( 'No people found.', 'your-textdomain' ),
		'not_found_in_trash'       => esc_html__( 'No people found in Trash.', 'your-textdomain' ),
		'parent_item_colon'        => esc_html__( 'Parent People:', 'your-textdomain' ),
		'all_items'                => esc_html__( 'All People', 'your-textdomain' ),
		'archives'                 => esc_html__( 'People Archives', 'your-textdomain' ),
		'attributes'               => esc_html__( 'People Attributes', 'your-textdomain' ),
		'insert_into_item'         => esc_html__( 'Insert into people', 'your-textdomain' ),
		'uploaded_to_this_item'    => esc_html__( 'Uploaded to this people', 'your-textdomain' ),
		'featured_image'           => esc_html__( 'Featured image', 'your-textdomain' ),
		'set_featured_image'       => esc_html__( 'Set featured image', 'your-textdomain' ),
		'remove_featured_image'    => esc_html__( 'Remove featured image', 'your-textdomain' ),
		'use_featured_image'       => esc_html__( 'Use as featured image', 'your-textdomain' ),
		'menu_name'                => esc_html__( 'People', 'your-textdomain' ),
		'filter_items_list'        => esc_html__( 'Filter people list', 'your-textdomain' ),
		'filter_by_date'           => esc_html__( '', 'your-textdomain' ),
		'items_list_navigation'    => esc_html__( 'People list navigation', 'your-textdomain' ),
		'items_list'               => esc_html__( 'People list', 'your-textdomain' ),
		'item_published'           => esc_html__( 'People published.', 'your-textdomain' ),
		'item_published_privately' => esc_html__( 'People published privately.', 'your-textdomain' ),
		'item_reverted_to_draft'   => esc_html__( 'People reverted to draft.', 'your-textdomain' ),
		'item_scheduled'           => esc_html__( 'People scheduled.', 'your-textdomain' ),
		'item_updated'             => esc_html__( 'People updated.', 'your-textdomain' ),
		'text_domain'              => esc_html__( 'your-textdomain', 'your-textdomain' ),
	];
	$args = [
		'label'               => esc_html__( 'People', 'your-textdomain' ),
		'labels'              => $labels,
		'description'         => '',
		'public'              => true,
		'hierarchical'        => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'show_ui'             => true,
		'show_in_nav_menus'   => true,
		'show_in_admin_bar'   => true,
		'show_in_rest'        => false,
		'query_var'           => true,
		'can_export'          => true,
		'delete_with_user'    => true,
		'has_archive'         => true,
		'rest_base'           => '',
		'show_in_menu'        => true,
		'menu_position'       => 6,
		'menu_icon'           => 'dashicons-admin-users',
		'capability_type'     => 'post',
		'supports'            => ['title', 'editor', 'thumbnail', 'comments'],
		'taxonomies'          => ['nationality'],
		'rewrite'             => [
			'with_front' => false,
			'feeds' => false
		],
	];

	register_post_type( 'people', $args );
}