<?php
add_action( 'init', 'tv_series_seasons' );
function tv_series_seasons() {
	$labels = [
		'name'                     => esc_html__( 'Seasons', 'tv-series-seasons' ),
		'singular_name'            => esc_html__( 'Season', 'tv-series-seasons' ),
		'add_new'                  => esc_html__( 'Add New', 'tv-series-seasons' ),
		'add_new_item'             => esc_html__( 'Add New Season', 'tv-series-seasons' ),
		'edit_item'                => esc_html__( 'Edit Season', 'tv-series-seasons' ),
		'new_item'                 => esc_html__( 'New Season', 'tv-series-seasons' ),
		'view_item'                => esc_html__( 'View Season', 'tv-series-seasons' ),
		'view_items'               => esc_html__( 'View Seasons', 'tv-series-seasons' ),
		'search_items'             => esc_html__( 'Search Seasons', 'tv-series-seasons' ),
		'not_found'                => esc_html__( 'No seasons found.', 'tv-series-seasons' ),
		'not_found_in_trash'       => esc_html__( 'No seasons found in Trash.', 'tv-series-seasons' ),
		'parent_item_colon'        => esc_html__( 'Parent Season:', 'tv-series-seasons' ),
		'all_items'                => esc_html__( 'All Seasons', 'tv-series-seasons' ),
		'archives'                 => esc_html__( 'Season Archives', 'tv-series-seasons' ),
		'attributes'               => esc_html__( 'Season Attributes', 'tv-series-seasons' ),
		'insert_into_item'         => esc_html__( 'Insert into season', 'tv-series-seasons' ),
		'uploaded_to_this_item'    => esc_html__( 'Uploaded to this season', 'tv-series-seasons' ),
		'featured_image'           => esc_html__( 'Featured image', 'tv-series-seasons' ),
		'set_featured_image'       => esc_html__( 'Set featured image', 'tv-series-seasons' ),
		'remove_featured_image'    => esc_html__( 'Remove featured image', 'tv-series-seasons' ),
		'use_featured_image'       => esc_html__( 'Use as featured image', 'tv-series-seasons' ),
		'menu_name'                => esc_html__( 'Seasons', 'tv-series-seasons' ),
		'filter_items_list'        => esc_html__( 'Filter seasons list', 'tv-series-seasons' ),
		'filter_by_date'           => esc_html__( '', 'tv-series-seasons' ),
		'items_list_navigation'    => esc_html__( 'Seasons list navigation', 'tv-series-seasons' ),
		'items_list'               => esc_html__( 'Seasons list', 'tv-series-seasons' ),
		'item_published'           => esc_html__( 'Season published.', 'tv-series-seasons' ),
		'item_published_privately' => esc_html__( 'Season published privately.', 'tv-series-seasons' ),
		'item_reverted_to_draft'   => esc_html__( 'Season reverted to draft.', 'tv-series-seasons' ),
		'item_scheduled'           => esc_html__( 'Season scheduled.', 'tv-series-seasons' ),
		'item_updated'             => esc_html__( 'Season updated.', 'tv-series-seasons' ),
		'text_domain'              => esc_html__( 'tv-series-seasons', 'tv-series-seasons' ),
	];
	$args = [
		'label'               => esc_html__( 'Seasons', 'tv-series-seasons' ),
		'labels'              => $labels,
		'description'         => '',
		'public'              => true,
		'hierarchical'        => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'show_ui'             => true,
		'show_in_nav_menus'   => true,
		'show_in_admin_bar'   => true,
		'show_in_rest'        => false,
		'query_var'           => true,
		'can_export'          => true,
		'delete_with_user'    => true,
		'has_archive'         => false,
		'rest_base'           => '',
		'show_in_menu'        => 'edit.php?post_type=tv',
		'menu_icon'           => 'dashicons-admin-generic',
		'capability_type'     => 'post',
		'supports'            => ['title', 'editor', 'thumbnail'],
		'taxonomies'          => [],
		'rewrite'             => [
			'with_front' => false,
		],
	];

	if(get_option( 'tmu_tv_series' ) === 'on') register_post_type( 'season', $args );
}